IOW-587: Site_Active added to Time Series Services
usgs/time-series-services pull request #118
Opened 2020-10-01 12:46 UTC by dsiemon2

IOW-587: Site_Active added to Time Series Services
Tests added

2020-10-01 15:53 UTC, kkehl-usgs commented on src/main/resources/mybatis/features.xml
> +            <if test="siteActive ==  TRUE">
extra whitespace after the equals sign?

2020-10-01 15:53 UTC, kkehl-usgs commented on src/main/java/gov/usgs/wma/waterdata/collections/CollectionsController.java
> +		//@Size(min=1, max=100, message="The Active Flag for Site monitoring locations ")
can we remove this?

2020-10-01 15:55 UTC, kkehl-usgs commented on src/test/resources/testResult/featureCollection/monitoring-locations/featureCollection_s19l10.json
> +
extra line

2020-10-01 15:56 UTC, kkehl-usgs approved these changes

2020-10-01 18:19 UTC, orosz-usgs requested changes

2020-10-01 18:19 UTC, orosz-usgs commented on pom.xml
> +                </executions>
extra space

2020-10-01 18:19 UTC, orosz-usgs commented on src/test/java/gov/usgs/wma/waterdata/collections/FeaturesFilterIT.java
> +            String compareFile = "featuresFilter/monitoring-locations/monitoring_location_type_multi_values.json";
The compare file is the same for both tests.

2020-10-01 18:19 UTC, orosz-usgs commented on src/test/resources/testResult/featureCollection/monitoring-locations/featureCollection.json
> +
extra line

2020-10-07 11:56 UTC, orosz-usgs requested changes

2020-10-07 11:56 UTC, orosz-usgs commented on src/test/resources/testResult/featuresFilter/monitoring-locations/monitoring_location_site_active_false.json
> +      "href": "https://unittest/api/observations/collections/monitoring-locations/items?f=json&startIndex=0&limit=10000"
This url should have '&siteActive=false'

2020-10-07 11:56 UTC, orosz-usgs commented on src/test/resources/testResult/featuresFilter/monitoring-locations/monitoring_location_site_active_true.json
> +      "href": "https://unittest/api/observations/collections/monitoring-locations/items?f=json&startIndex=0&limit=10000"
This url should have '&siteActive=true'

2020-10-13 19:45 UTC, merged